name: Deploy

on:
  workflow_run:
    workflows: ['Release'] # Name of the workflow to wait for (same as the name in release.yml)
    types:
      - completed # Runs when the workflow is completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }} # Only runs if the release succeeded
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run deployment process
        run: echo "Deploying to production"
